{"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/LocalizedError-Implementations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"LocalizedError.errorDescription","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierrorresponse\/errordescription"]}],"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"OpenAI"}],"extendedModule":"OpenAI","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"errorDescription","symbolKind":"property","externalID":"s:6OpenAI16APIErrorResponseV16errorDescriptionSSSgvp"},"references":{"doc://OpenAI/documentation/OpenAI/APIErrorResponse/errorDescription":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","title":"errorDescription","abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription","type":"topic","url":"\/documentation\/openai\/apierrorresponse\/errordescription","kind":"symbol"},"doc://OpenAI/documentation/OpenAI":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","role":"collection","url":"\/documentation\/openai","title":"OpenAI"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"kind":"article","type":"topic","url":"\/documentation\/openai\/apierrorresponse\/localizederror-implementations","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/LocalizedError-Implementations"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse":{"type":"topic","url":"\/documentation\/openai\/apierrorresponse","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"APIErrorResponse","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"APIErrorResponse"}],"title":"APIErrorResponse","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"}}}