{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"OpenAI"}],"role":"collectionGroup","roleHeading":"API Collection","title":"LocalizedError Implementations"},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/LocalizedError-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierrorresponse\/localizederror-implementations"]}],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"]]},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/recoverySuggestion"]}],"sections":[],"references":{"doc://OpenAI/documentation/OpenAI/APIErrorResponse/errorDescription":{"abstract":[],"title":"errorDescription","kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/openai\/apierrorresponse\/errordescription"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/recoverySuggestion":{"title":"recoverySuggestion","type":"topic","role":"symbol","url":"\/documentation\/openai\/apierrorresponse\/recoverysuggestion","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/recoverySuggestion"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/failureReason":{"url":"\/documentation\/openai\/apierrorresponse\/failurereason","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"failureReason","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/failureReason","type":"topic","abstract":[]},"doc://OpenAI/documentation/OpenAI":{"url":"\/documentation\/openai","title":"OpenAI","role":"collection","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","kind":"symbol","abstract":[],"type":"topic"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse":{"kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse","title":"APIErrorResponse","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIErrorResponse"}],"navigatorTitle":[{"text":"APIErrorResponse","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/openai\/apierrorresponse"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/helpAnchor":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/helpAnchor","kind":"symbol","title":"helpAnchor","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/openai\/apierrorresponse\/helpanchor"}}}