{"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"],"generated":true}],"variants":[{"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"collectionGroup","modules":[{"name":"OpenAI"}],"roleHeading":"API Collection","title":"LocalizedError Implementations"},"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"references":{"doc://OpenAI/documentation/OpenAI/APIError":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIError"}],"title":"APIError","navigatorTitle":[{"text":"APIError","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/openai\/apierror"},"doc://OpenAI/documentation/OpenAI":{"type":"topic","kind":"symbol","url":"\/documentation\/openai","role":"collection","title":"OpenAI","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","abstract":[]},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"url":"\/documentation\/openai\/apierror\/errordescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[],"kind":"symbol","title":"errorDescription","type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription"},"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"url":"\/documentation\/openai\/apierror\/helpanchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[],"kind":"symbol","title":"helpAnchor","type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor"},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"url":"\/documentation\/openai\/apierror\/failurereason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[],"kind":"symbol","title":"failureReason","type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason"},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"url":"\/documentation\/openai\/apierror\/recoverysuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[],"kind":"symbol","title":"recoverySuggestion","type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"}}}