{"kind":"article","variants":[{"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"],"generated":true,"title":"Instance Properties"}],"sections":[],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"OpenAI"}],"title":"LocalizedError Implementations"},"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"references":{"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"title":"errorDescription","url":"\/documentation\/openai\/apierror\/errordescription","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","type":"topic","kind":"symbol"},"doc://OpenAI/documentation/OpenAI":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","role":"collection","url":"\/documentation\/openai","title":"OpenAI"},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"url":"\/documentation\/openai\/apierror\/failurereason","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"failureReason","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","role":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"APIError"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","title":"APIError","url":"\/documentation\/openai\/apierror","navigatorTitle":[{"kind":"identifier","text":"APIError"}],"abstract":[]},"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[],"title":"helpAnchor","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","url":"\/documentation\/openai\/apierror\/helpanchor","type":"topic","kind":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/openai\/apierror\/recoverysuggestion","title":"recoverySuggestion","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion","role":"symbol"}}}