{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierror\/errordescription"]}],"kind":"symbol","identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"OpenAI"}],"title":"errorDescription","role":"symbol","externalID":"s:6OpenAI8APIErrorV16errorDescriptionSSSgvp","roleHeading":"Instance Property","symbolKind":"property","extendedModule":"OpenAI","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"references":{"doc://OpenAI/documentation/OpenAI":{"url":"\/documentation\/openai","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","abstract":[],"type":"topic","role":"collection","kind":"symbol","title":"OpenAI"},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"abstract":[],"kind":"symbol","type":"topic","title":"errorDescription","url":"\/documentation\/openai\/apierror\/errordescription","role":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}]},"doc://OpenAI/documentation/OpenAI/APIError/LocalizedError-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","type":"topic","title":"LocalizedError Implementations","url":"\/documentation\/openai\/apierror\/localizederror-implementations","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations"},"doc://OpenAI/documentation/OpenAI/APIError":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"APIError"}],"url":"\/documentation\/openai\/apierror","title":"APIError","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"APIError"}],"type":"topic","kind":"symbol"}}}