{"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"metadata":{"roleHeading":"API Collection","title":"LocalizedError Implementations","modules":[{"name":"OpenAI"}],"role":"collectionGroup"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"]}],"references":{"doc://OpenAI/documentation/OpenAI/APIError":{"type":"topic","kind":"symbol","abstract":[],"title":"APIError","role":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","url":"\/documentation\/openai\/apierror","navigatorTitle":[{"text":"APIError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"APIError","kind":"identifier"}]},"doc://OpenAI/documentation/OpenAI":{"abstract":[],"type":"topic","title":"OpenAI","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","kind":"symbol","role":"collection","url":"\/documentation\/openai"},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"abstract":[],"title":"recoverySuggestion","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/openai\/apierror\/recoverysuggestion"},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"errorDescription","url":"\/documentation\/openai\/apierror\/errordescription","kind":"symbol","type":"topic"},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","kind":"symbol","url":"\/documentation\/openai\/apierror\/failurereason","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"failureReason","type":"topic"},"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"role":"symbol","type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","abstract":[],"kind":"symbol","title":"helpAnchor","url":"\/documentation\/openai\/apierror\/helpanchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]}}}