{"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"topicSections":[{"identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"],"title":"Instance Properties","generated":true}],"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","modules":[{"name":"OpenAI"}],"role":"collectionGroup","title":"LocalizedError Implementations"},"references":{"doc://OpenAI/documentation/OpenAI/APIError":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"APIError"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","title":"APIError","type":"topic","abstract":[],"url":"\/documentation\/openai\/apierror","navigatorTitle":[{"kind":"identifier","text":"APIError"}]},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"type":"topic","title":"recoverySuggestion","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/openai\/apierror\/recoverysuggestion","abstract":[],"role":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"},"doc://OpenAI/documentation/OpenAI":{"title":"OpenAI","type":"topic","url":"\/documentation\/openai","kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","role":"collection","abstract":[]},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"type":"topic","title":"errorDescription","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/openai\/apierror\/errordescription","abstract":[],"role":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription"},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","kind":"symbol","role":"symbol","abstract":[],"type":"topic","title":"failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/openai\/apierror\/failurereason"},"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"type":"topic","title":"helpAnchor","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/openai\/apierror\/helpanchor","abstract":[],"role":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor"}}}