{"metadata":{"title":"LocalizedError Implementations","modules":[{"name":"OpenAI"}],"roleHeading":"API Collection","role":"collectionGroup"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"],"generated":true}],"kind":"article","identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"]}],"references":{"doc://OpenAI/documentation/OpenAI/APIError":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"APIError","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","navigatorTitle":[{"text":"APIError","kind":"identifier"}],"kind":"symbol","title":"APIError","type":"topic","url":"\/documentation\/openai\/apierror","role":"symbol"},"doc://OpenAI/documentation/OpenAI":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","url":"\/documentation\/openai","title":"OpenAI","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI"},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"title":"recoverySuggestion","abstract":[],"kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion","type":"topic","url":"\/documentation\/openai\/apierror\/recoverysuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","kind":"symbol","title":"helpAnchor","type":"topic","url":"\/documentation\/openai\/apierror\/helpanchor","role":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"title":"failureReason","abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","url":"\/documentation\/openai\/apierror\/failurereason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"title":"errorDescription","abstract":[],"kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","type":"topic","url":"\/documentation\/openai\/apierror\/errordescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol"}}}