{"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations","interfaceLanguage":"swift"},"kind":"article","topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"]}],"sections":[],"metadata":{"role":"collectionGroup","modules":[{"name":"OpenAI"}],"roleHeading":"API Collection","title":"LocalizedError Implementations"},"references":{"doc://OpenAI/documentation/OpenAI/APIError":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"APIError","kind":"identifier"}],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","abstract":[],"role":"symbol","type":"topic","navigatorTitle":[{"text":"APIError","kind":"identifier"}],"url":"\/documentation\/openai\/apierror","kind":"symbol","title":"APIError"},"doc://OpenAI/documentation/OpenAI":{"url":"\/documentation\/openai","role":"collection","kind":"symbol","type":"topic","title":"OpenAI","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","abstract":[]},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","kind":"symbol","type":"topic","title":"errorDescription","abstract":[],"url":"\/documentation\/openai\/apierror\/errordescription","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","kind":"symbol","type":"topic","title":"failureReason","abstract":[],"url":"\/documentation\/openai\/apierror\/failurereason","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]},"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","kind":"symbol","type":"topic","title":"helpAnchor","abstract":[],"url":"\/documentation\/openai\/apierror\/helpanchor","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion","kind":"symbol","type":"topic","title":"recoverySuggestion","abstract":[],"url":"\/documentation\/openai\/apierror\/recoverysuggestion","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}}}