{"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError"]]},"topicSections":[{"identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion"],"title":"Instance Properties","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/LocalizedError-Implementations"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"OpenAI"}],"role":"collectionGroup","roleHeading":"API Collection","title":"LocalizedError Implementations"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierror\/localizederror-implementations"]}],"references":{"doc://OpenAI/documentation/OpenAI/APIError/helpAnchor":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"helpAnchor","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/helpAnchor","url":"\/documentation\/openai\/apierror\/helpanchor","abstract":[],"kind":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError/recoverySuggestion":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"recoverySuggestion","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/recoverySuggestion","url":"\/documentation\/openai\/apierror\/recoverysuggestion","abstract":[],"kind":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError/errorDescription":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"errorDescription","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/errorDescription","url":"\/documentation\/openai\/apierror\/errordescription","abstract":[],"kind":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"APIError","kind":"identifier"}],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/openai\/apierror","title":"APIError","role":"symbol","navigatorTitle":[{"text":"APIError","kind":"identifier"}]},"doc://OpenAI/documentation/OpenAI/APIError/failureReason":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"failureReason","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError\/failureReason","url":"\/documentation\/openai\/apierror\/failurereason","abstract":[],"kind":"symbol"},"doc://OpenAI/documentation/OpenAI":{"abstract":[],"type":"topic","role":"collection","url":"\/documentation\/openai","title":"OpenAI","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","kind":"symbol"}}}