{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierrorresponse\/error"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6OpenAI8APIErrorV","text":"APIError","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","kind":"typeIdentifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/error","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"OpenAI"}],"externalID":"s:6OpenAI16APIErrorResponseV5errorAA0C0Vvp","title":"error","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"text":"APIError","kind":"typeIdentifier","preciseIdentifier":"s:6OpenAI8APIErrorV"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"references":{"doc://OpenAI/documentation/OpenAI":{"abstract":[],"type":"topic","title":"OpenAI","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","kind":"symbol","role":"collection","url":"\/documentation\/openai"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse":{"kind":"symbol","title":"APIErrorResponse","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APIErrorResponse","kind":"identifier"}],"navigatorTitle":[{"text":"APIErrorResponse","kind":"identifier"}],"url":"\/documentation\/openai\/apierrorresponse","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse","abstract":[],"role":"symbol"},"doc://OpenAI/documentation/OpenAI/APIError":{"type":"topic","kind":"symbol","abstract":[],"title":"APIError","role":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIError","url":"\/documentation\/openai\/apierror","navigatorTitle":[{"text":"APIError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"APIError","kind":"identifier"}]},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/error":{"kind":"symbol","title":"error","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6OpenAI8APIErrorV","text":"APIError","kind":"typeIdentifier"}],"url":"\/documentation\/openai\/apierrorresponse\/error","abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/error","role":"symbol"}}}