{"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierrorresponse\/localizederror-implementations"]}],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/LocalizedError-Implementations"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/recoverySuggestion"],"generated":true}],"sections":[],"metadata":{"modules":[{"name":"OpenAI"}],"roleHeading":"API Collection","role":"collectionGroup","title":"LocalizedError Implementations"},"references":{"doc://OpenAI/documentation/OpenAI/APIErrorResponse":{"title":"APIErrorResponse","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"APIErrorResponse"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"APIErrorResponse","kind":"identifier"}],"abstract":[],"url":"\/documentation\/openai\/apierrorresponse","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/recoverySuggestion":{"title":"recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/recoverySuggestion","url":"\/documentation\/openai\/apierrorresponse\/recoverysuggestion"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/errorDescription":{"title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/openai\/apierrorresponse\/errordescription","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/helpAnchor":{"title":"helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/helpAnchor","url":"\/documentation\/openai\/apierrorresponse\/helpanchor"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/failureReason":{"title":"failureReason","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","abstract":[],"url":"\/documentation\/openai\/apierrorresponse\/failurereason","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/failureReason"},"doc://OpenAI/documentation/OpenAI":{"abstract":[],"role":"collection","url":"\/documentation\/openai","title":"OpenAI","kind":"symbol","type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI"}}}