{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/openai\/apierrorresponse\/localizederror-implementations"]}],"metadata":{"modules":[{"name":"OpenAI"}],"title":"LocalizedError Implementations","role":"collectionGroup","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"]]},"kind":"article","identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/LocalizedError-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/recoverySuggestion"],"generated":true}],"references":{"doc://OpenAI/documentation/OpenAI/APIErrorResponse/errorDescription":{"title":"errorDescription","abstract":[],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription","url":"\/documentation\/openai\/apierrorresponse\/errordescription"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/helpAnchor":{"type":"topic","title":"helpAnchor","role":"symbol","url":"\/documentation\/openai\/apierrorresponse\/helpanchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/helpAnchor"},"doc://OpenAI/documentation/OpenAI":{"type":"topic","kind":"symbol","abstract":[],"role":"collection","url":"\/documentation\/openai","title":"OpenAI","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/recoverySuggestion":{"abstract":[],"type":"topic","kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/recoverySuggestion","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/openai\/apierrorresponse\/recoverysuggestion","title":"recoverySuggestion"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/failureReason":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"url":"\/documentation\/openai\/apierrorresponse\/failurereason","title":"failureReason","kind":"symbol","role":"symbol","type":"topic","abstract":[]},"doc://OpenAI/documentation/OpenAI/APIErrorResponse":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"APIErrorResponse","kind":"identifier"}],"title":"APIErrorResponse","abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/openai\/apierrorresponse","navigatorTitle":[{"kind":"identifier","text":"APIErrorResponse"}],"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"}}}