{"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"title":"LocalizedError Implementations","roleHeading":"API Collection","modules":[{"name":"OpenAI"}],"role":"collectionGroup"},"identifier":{"url":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/LocalizedError-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/openai\/apierrorresponse\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/OpenAI\/documentation\/OpenAI","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/failureReason","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/helpAnchor","doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/recoverySuggestion"],"title":"Instance Properties"}],"references":{"doc://OpenAI/documentation/OpenAI/APIErrorResponse/failureReason":{"title":"failureReason","kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/failureReason","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/openai\/apierrorresponse\/failurereason"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/helpAnchor":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/helpAnchor","kind":"symbol","url":"\/documentation\/openai\/apierrorresponse\/helpanchor","role":"symbol","title":"helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse":{"kind":"symbol","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse","abstract":[],"url":"\/documentation\/openai\/apierrorresponse","title":"APIErrorResponse","role":"symbol","navigatorTitle":[{"text":"APIErrorResponse","kind":"identifier"}],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"APIErrorResponse"}]},"doc://OpenAI/documentation/OpenAI":{"abstract":[],"type":"topic","role":"collection","url":"\/documentation\/openai","title":"OpenAI","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI","kind":"symbol"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/recoverySuggestion":{"identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/recoverySuggestion","url":"\/documentation\/openai\/apierrorresponse\/recoverysuggestion","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"abstract":[],"title":"recoverySuggestion"},"doc://OpenAI/documentation/OpenAI/APIErrorResponse/errorDescription":{"abstract":[],"title":"errorDescription","url":"\/documentation\/openai\/apierrorresponse\/errordescription","type":"topic","identifier":"doc:\/\/OpenAI\/documentation\/OpenAI\/APIErrorResponse\/errorDescription","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"role":"symbol"}}}